name: clubhouse_ui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  pull_to_refresh: ^2.0.0

# flutter_launcher_icons:
#   image_path: "assets/images/logo.jpg"
#   android: true
#   ios: true

# flutter_launcher_name:
#   name: "Clubhouse UI"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Italic.ttf
        - asset: fonts/OpenSans-BoldItalic.ttf
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-ExtraBold.ttf
        - asset: fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: fonts/OpenSans-Light.ttf
        - asset: fonts/OpenSans-LightItalic.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
        - asset: fonts/OpenSans-SemiBoldItalic.ttf
